[package]
name = "pianophase"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
num-rational = "0.4.2"
num-traits = "0.2.19"
rustysynth = "1.3.1"
sfml = "0.21.0"
tinyaudio = "0.1.4"
