[package]
name = "pianophase"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
macroquad = "0.4.12"
midly = "0.5.3"
num-rational = "0.4.2"
num-traits = "0.2.19"
rustysynth = "1.3.1"
smufl = "0.2.1"
tinyaudio = "0.1.4"
